### ISSUE TITLE
Doctrine Annotations loader is registered too late.

### ISSUE THREAD

**Issue by mochja** [Kdyby/Annotations#5]
We use some services with `run` tag, those services uses some `Entity` and we run into this exception
```
Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@Doctrine\ORM\Mapping\MappedSuperclass" in class Kdyby\Doctrine\Entities\BaseEntity does not exist, or could not be auto-loaded.
```

I've found out that `Doctrine\Common\Annotations\AnnotationRegistry::registerLoader` is calling after the services are initialized, which should cause the problem.

```php
class Container_XXX {
	// ....
	public function initialize()
	{
		date_default_timezone_set('Europe/Amsterdam');
		$this->getService('events.manager')->createEvent(array('Nette\DI\Container', 'onInitialize'))->dispatch($this);
		$this->getService(155); // This service uses Doctrine Entity
		Nette\Reflection\AnnotationsParser::setCacheStorage($this->getByType("Nette\Caching\IStorage"));
		Nette\Reflection\AnnotationsParser::$autoRefresh = FALSE;
		Doctrine\Common\Annotations\AnnotationRegistry::registerLoader("class_exists");
		Kdyby\Doctrine\Diagnostics\Panel::registerBluescreen($this);
	}
}
```

Simple fix for this is to put line below in bootstrap file
```php
Doctrine\Common\Annotations\AnnotationRegistry::registerFile( __VENDOR_DIR__ . '/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/DoctrineAnnotations.php');
```

**Comment by enumag** [comment]
The obvious fix would be to use `Container::onInitialize` event to register the loader. Problem is that it would make Kdyby/Annotations dependent on Kdyby/Events which is bad.

**Comment by fprochazka** [comment]
Yeah... don't think making it dependent would be a good idea. Better would be to duplicate the hack to prepend the code.

**Comment by enumag** [comment]
I don't wish to duplicate the code. How about adding an option `earlyInitialization` to DI extension which would default to false and would require Kdyby/Events to be installed if someone enabled it?

**Comment by enumag** [comment]
ping @fprochazka

**Comment by fprochazka** [comment]
@enumag https://twitter.com/bonzoesc/status/442003113910603776

**Comment by fprochazka** [comment]
How about this? :)

**Comment by enumag** [comment]
Nice! :-)
