### ISSUE TITLE
Cache invalidation notes

### ISSUE THREAD

**Issue by enumag** [Kdyby/Annotations#7]
I've installed symfony demo project in order to look how annotations invalidation works for both Doctrine/ORM and Symfony/Validator.

The interesting fact is that default configuration doesn’t actualy use cache for metadata, only for the annotations themselves.
- Validator: [LazyLoadyingMetadataFactory](https://github.com/symfony/validator/blob/master/Mapping/Factory/LazyLoadingMetadataFactory.php) gets null as cache.
- Doctrine: [ClassMetadataFactory](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php) extends [AbstractClassMetadataFactory](https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php) and gets [ArrayCache](https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/ArrayCache.php) as cacheDriver. Which means the meatadata are only cached for the current request.

This applies for both dev and prod environments.

The Annotations are cached using [FileCacheReader](https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Common/Annotations/FileCacheReader.php) which has the ability to invalidate the cache if set to debug.

I’m considering using something like this instead of the [solution I suggested earlier for Kdyby/DoctrineCache](https://github.com/Kdyby/DoctrineCache/pull/7#issuecomment-144193886).

**I'd like to use the same as Symfony for debug mode (maybe with in-memory cache for Validator), but with some additional cache for metadata in production mode. Also I'd like to stop using the delegation to Nette/Caching by default.**

What do you think? (cc @fprochazka)

**Comment by fprochazka** [comment]
I think the delegation to nette\caching is very useful if you just don't care and want it working.
Using array drivers for debug mode (only!) is something I'm not against :)

**Comment by enumag** [comment]
I don't understand your point about nette\caching delegation. From my point of view it only makes invalidation ugly and problematic. If we change the default configuration to not delegate it will also work fine for those who don't care.

**Comment by fprochazka** [comment]
I didn't realize there is a [FilesystemCache](https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/FilesystemCache.php) implemented, in that case, the defaut should be probably renamed to `delegate`, and the default should be FilesystemCache (and [ArrayCache](https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/ArrayCache.php) in debug mode).

**Comment by enumag** [comment]
Fine, I'll look into it then.

**Comment by enumag** [comment]
Probably unsolved but this issue is outdated. I'll open a new one if I find out anything.
